feed/urls.py
from . import views
from django.urls import include, path

urlpatterns = [
    path("", views.PostList.as_view(), name="feed"),
    path('<str:author>/', views.post_by_user, name='post_by_user'),
    path("<str:author>/create/", views.post_create, name="post_create"),
    path("<str:author>/<slug:slug>/", views.post_detail , name="post_detail"),
    path("<str:author>/<slug:slug>/update", views.post_update, name="post_update"),
    path("<str:author>/<slug:slug>/delete", views.post_delete, name="post_delete"),
    path('<str:author>/<slug:slug>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),

]

kepo/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from myaccount import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', account_views.homepage, name='homepage'),
    #Authentication
    path('signup/', account_views.sign_up, name='sign_up'),
    path('signout/', account_views.sign_out, name='sign_out'),
    path('signin/', account_views.sign_in, name='sign_in'),

    #Webapps
    path('feed/', include('feed.urls')),
    path('journal/', include('myjournal.urls')),
    path('account/', include('myaccount.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myaccount/urls.py
from django.urls import path
from myaccount import views
app_name = 'myaccount'

urlpatterns = [
      path('', views.account_settings, name='account_settings'),
      path('update/', views.account_update, name='account_update'),
      path('password/update', views.password_update, name='password_update'),
      path('sign_in/', views.sign_in, name="sign_in")
]

myjournal/urls.py
from django.urls import path
from django.conf.urls import url

from myjournal import views

app_name = 'myjournal'
urlpatterns = [
    path('today/', views.journal_today, name='journal_today'),
    path('today/morning/create', views.morning_create, name='morning_create'),
    path('morning/<int:morningjournal_pk>/view', views.morning_update, name='morning_update'),
    path('morning/<int:morningjournal_pk>/delete', views.morning_delete, name='morning_delete'),
    path('today/evening/create', views.evening_create, name='evening_create'),
    path('evening/<int:eveningjournal_pk>/view', views.evening_update, name='evening_update'),
    path('evening/<int:eveningjournal_pk>/delete', views.evening_delete, name='evening_delete'),
    path('month/', views.CalendarView.as_view(), name='calendar'),
    path('month/morning/<int:morningjournal_pk>/view', views.morning_update, name='morning_update'),
    path('month/evening/<int:eveningjournal_pk>/view', views.evening_update, name='evening_update'),

]

feed/models.py
from django.db import models
from django.contrib.auth.models import User
import readtime

STATUS = ((0, "Draft"), (1, "Publish"))

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    img = models.ImageField(upload_to="media/myfeed")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts", default=1
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("post_detail", kwargs={"author": str(self.author.username), "slug": str(self.slug)})
    
    def get_read_time(self):
       result = readtime.of_text(self.content)
       return result.text

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    commenter = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_comments", default=1
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.commenter)

feed/forms.py
from .models import Comment, Post
from django import forms

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        prepopulated_fields = {'slug': ('title')}
        fields = ['title', 'slug', 'img', 'content', 'status']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['commenter', 'body']

feed/views.py
from django.views import generic
from .models import Post, Comment
from .forms import CommentForm, PostForm
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import messages

@login_required
def post_create(request, author):
    author=request.user
    if request.method == 'GET':
        return render(request, 'feed/post_create.html', {'form':PostForm()})
    else:
        try:
            form = PostForm(data=request.POST, files=request.FILES)
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return render(request, 'feed/feed.html', {'info':'Post created!'})
        except ValueError:
            return render(request, 'feed/post_create.html', {'form':PostForm(), 'error':'Bad data passed in. Try again.'})

@login_required
def post_delete(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        post.delete()
        return render(request, 'feed/feed.html', {'post':post, 'error':'The post has been deleted'})

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "feed/feed.html"
    paginate_by = 9

    # Function to test whether the current user is the author of the post he wants to edit
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

#Allow public to see
def post_by_user(request, author):
    user = request.user

    posts = Post.objects.filter(author__username=author,status=1).order_by("-created_on")
    drafts = Post.objects.filter(author__username=author,status=0).order_by("-created_on")
    return render(request, 'feed/post_user.html', {'posts':posts,'drafts':drafts,'author':author})

def post_detail(request, slug, author):
    template_name = "feed/post_detail.html"
    post = get_object_or_404(Post, author__username=author, slug=slug)
    comments = post.comments.filter(active=True).order_by("-created_on")
    new_comment = None

    # Comment posted
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.commenter = request.user
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(
        request,
        template_name,
        {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
        },
    )

@login_required
def post_update(request, slug, author):
    post = get_object_or_404(Post, slug=slug, author__username=author)
    if request.method == 'GET':
        form = PostForm(instance=post)
        return render(request, 'feed/post_update.html', {'form':form})
    else:
        try:
            form = PostForm(request.POST, request.FILES, instance=post)
            form.save()
            #Redirecting to main feed page because if slug has been changed, the url reverse will not work
            messages.success(request, 'Profile details updated.')
            return redirect('post_detail', author=author, slug=slug)
        except ValueError:
            return render(request, 'feed/post_update.html', {'form':form, 'error':'Bad info passed in. Try again?'})


@login_required
def post_delete(request, post_pk):
    form = get_object_or_404(Post, pk=post_pk, author=request.user)
    if request.method == 'POST':
        form.delete()
        return HttpResponseRedirect('feed/post_detail.html')

@login_required
def comment_delete(request, author, slug, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk, commenter=request.user)
    post = get_object_or_404(Post, slug=slug, author__username=author)
    if request.method == 'POST':
        comment.delete()
        #To fix: adding message that the comment has been deleted
        return redirect('post_detail', author=author, slug=slug)

feed/templates/feed/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="KEPO is designed for curious learners and sharers built with Python and Django framework ">
    <meta name="author" content="Kaye So Kua">
    <meta name="generator" content="Hugo 0.80.0">
    <title>KEPO · Curious Learning and Sharing</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/feed.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="icon" type="image/png"  href="{% static 'images/kepo-uni.png' %}">

    <style>
    .bg-pelorous {
        background:#3CC5C5;
    }
    textarea#id_body {
      width: 100%!important;
      max-width: 400px;
      resize: none;
      background: var(--kp-mischka);
      transition: 0.5s ease-in;
      border: 0
      }

    textarea#id_body:focus {
      outline: none;
      background: var(--kp-hawkesblue);
    }
    </style>

    <!-- Custom styles for this template -->
    <link href="offcanvas.css" rel="stylesheet">
  </head>
  <body class="bg-light">
    
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-pelorous" aria-label="Main navigation">
  <div class="container">
    <a class="navbar-brand" href="{% url 'feed' %}">kepo</a>
    <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="offcanvas" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'myjournal:journal_today' %}">My Journal</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'feed' %}">My Feed</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myaccount:account_settings' %}">My Account</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>
     

<div class="nav-scroller bg--body shadow-sm">
    <div class="container">
        <nav class="nav nav-underline" aria-label="Secondary navigation">
    <a class="nav-link active" aria-current="page" href="{% url 'post_create' user.username %}">Write A Post</a>
    <a class="nav-link" href="{% url 'post_by_user' user.username %}">
      My Posts
      
    </a>
    <a class="nav-link" href="#" style="float:right">
        You are currently logged in as
      <span class="badge bg-secondary text-white rounded-pill align-text-bottom">
      {{user.username}}</span>
    </a>
  </nav>
    </div>
</div>
{% else %}
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-pelorous" aria-label="Main navigation">
  <div class="container">
    <a class="navbar-brand" href="#">kepo</a>
    <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="offcanvas" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'feed' %}"> Feed</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'sign_up' %}"> Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'sign_in' %}"> Sign In</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>
     
{% endif %}


<main class="container">
  {% block content %}{% endblock %}
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
<script async src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous"></script>


</body>
</html>

feed/templates/feed/feed.html
{% extends "feed/base.html" %}

{% block content %}
{% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
{% if success %}<div class="alert alert-success" role="alert">{{ success }}</div>{% endif %}
  
  {% load humanize %}
  
  <h1 class="display-6 my-5">Get Inspired <i class="bi bi-lightning"></i></h1> 
  <div class="row" data-masonry='{"percentPosition": true }'>
    {% for post in post_list %}
    <!-- the feed post starts here -->
    <div class="col-sm-6 col-lg-4 mb-4">
      <div class="card shadow-sm">
        
        <div class="card-body">
        
        <h3 class="feedpost-title mt-1 mb-1"><a href="{% url 'post_detail' post.author post.slug  %}">{{ post.title|safe }}</a></h3>

        <p class="card-text text-center"><small>Published {{ post.created_on | naturaltime }} {{readtime_post}}
        
         by <a href="{% url 'post_by_user' post.author %}">{{ post.author }}</a> | {{post.get_read_time}}</small>
        </p>
               

        <img class="bd-placeholder-img card-img-top" width="100%" height="auto" src="{{ post.img.url }}" style="border: 1px solid #ccc"/>
              
        
          
      
        </div>
      </div>
    </div>
    <!-- and the feed post ends here -->
    {% endfor %}

  </div>

{% if is_paginated %}
<nav aria-label="Page navigation conatiner"></nav>
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
  {% endif %}
  {% if page_obj.has_next %}
  <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

  {% endif %}
</ul>
</nav>
{% endif %}
{% endblock %}

feed/templates/feed/post_create.html
{% extends "feed/base.html" %}

{% block content %}
    <h2 class="mt-5">Create New Post</h2>
    <div class="row">
        <div class="col-md-8">
            {% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
            
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-12">
                <div class="form-group mb-3">
                    <p class="lead">Title</p>
                    <input type="text" name="title" class="form-control form-control-lg" id="id_title">
                </div>
                <div class="form-group mb-3">
                    <p class="lead">Custom URL</p>
                    <input type="text" name="slug" class="form-control form-control-lg" id="id_slug">
                </div>
                <div class="form-group mb-3">
                    <p class="lead">Main Content</p>
                    <textarea name="content" class="form-control form-control-lg" id="id_content"></textarea>
                </div>
                <div class="form-group mb-3">
                    <p class="lead">Featured Image</p>
                    <input type="file" name="img" class="form-control form-control-lg" id="id_img">
                </div>
                <div class="form-group mb-3">
                    <p class="lead">Status</p>
                    <select name="status" id="id_status" class="form-select form-select-lg" required>
                        <option value="0" >Draft</option>
                        <option value="1">Publish</option>
                    </select>
                </div>
                <div class="form-group mb-3">
                    <button type="submit" class="btn btn-lg text-white btn-info">Save Entry</button>
                </div>
            </div>
            </form>

            </div>
             
    </div> 

{% endblock %}

feed/templates/feed/post_detail.html
{% extends "feed/base.html" %}

{% block content %}
{% load crispy_forms_tags %}

<div class="container">
  <div class="row">
  <div class="col-md-8 mb-3">
      {% if messages %}
            {% for message in messages %}
              <div class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %}" role="alert">
              {{ message }}
              </div>
            {% endfor %}
          {% endif %}
    </div>
        
    <div class="col-md-8 card mb-4 mt-3 left top">
   

      <div class="card-body">
 

          
        <h1 style="text-transform:capitalize">{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p>{% if user.is_authenticated and user == post.author %}<a href="{% url 'post_update' post.author post.slug %}">Edit post</a> |
          <a href="#" class="link-danger"><s>Delete</s></a>


          {% else %}Posted by <a href="{% url 'post_by_user' post.author %}">{{ post.author }}</a>
          {% endif %}| {{ post.created_on }}
        </p>
        <div class="card-text">
        <a class="link-primary" data-bs-toggle="modal" data-bs-target="#enlarge_img"><img src="{{ post.img.url }}" alt="Image for {{ post.title }}"  style="width:40%; max-width:350px; height:auto; float:left; margin-right:1em" class="img-thumbnail"></a>

       {{ post.content | linebreaks }}
        </div>
        

      </div>
    </div>

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
       {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment has been published!
        </div>
        {% endif %}

        {% if error %}
        <div class="alert alert-danger" role="alert">
         {{error}}
        </div>
        {% endif %}

        <!-- comments -->
        {% if comments %}

            {% with comments.count as total_comments %}
            <h3>{{ total_comments }} comment/s</h3>
            {% endwith %}
          
        {% for comment in comments %}
        
        <div class="comments" style="padding: 10px;">
          <p class="lead">
          <strong>{{ comment.commenter }}</strong> : {{ comment.body | linebreaks }}
          </p>
          <small>
          {{ comment.created_on }}
          {% if user.is_authenticated and user == comment.commenter %}   
              <form action = "{% url 'comment_delete' post.author post.slug comment.id %}" method = "POST">
              {% csrf_token %}
              <button class="btn btn-secondary">Delete this comment</button>
              </form>
          {% endif %}
          </small>
           
          
        </div>
        <hr class="my-2">

        {% endfor %}
         {% else %}
           <h3>Be the first to comment!</h3>
           {% endif %}
        {% if user.is_authenticated %}
            <button type="submit" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#modal_comment">Leave a comment</button>
        {% else %}
            Sign up / Sign In to leave a comment
        {% endif %}
      </div>
    </div>

  </div>
</div>

    <!-- Enlarge Image -->
    <div class="modal fade" id="enlarge_img" tabindex="-1" aria-labelledby="exampleModal" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-body">
            <img src="{{ post.img.url }}" width="100%" height="auto">
          </div>
        </div>
      </div>
    </div>

     <!-- Comment Form -->
    <ddiv class="modal fade" id="modal_comment" tabindex="-1" aria-labelledby="exampleModal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Leave a comment as {{user.username}}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
           <form method="post">
           
           {% csrf_token %}
           <div style="display:none;">{{comment_form.as_p}}</div>
          <textarea name="body" cols="40" rows="10" required="" id="id_body"></textarea>
          
          </div>
          <div class="modal-footer">
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
          </form>
          </div>
        </div>
      </div>
    </div>


{% endblock content %}

feed/templates/feed/post_update.html
{% extends "feed/base.html" %}

{% block content %}
    <h2 class="mt-5">Update Post</h2>
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
                <div class="alert">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{form.as_p}}
             <button type="submit" class="btn btn-lg text-white btn-info">Save Entry</button>
            </form>

            </div>
             
    </div> 

{% endblock %}

feed/templates/feed/post_update2.html
{% extends "feed/base.html" %}

{% block content %}
    <h2 class="mt-5">Update Post</h2>
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
                <div class="alert">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="col-md-12">
                <div class="form-group mb-3">
                    <p class="lead">Title</p>
                    <input type="text" name="title" class="form-control form-control-lg" id="id_title" value="{{post.title}}">
                </div>
                <div class="form-group mb-3">
                    <p class="lead">Custom URL</p>
                    <input type="text" name="slug" class="form-control form-control-lg" id="id_slug" value="{{post.slug}}" disabled>
                </div>
                <div class="form-group mb-3">
                    <p class="lead">Main Content</p>
                    <textarea name="content" class="form-control form-control-lg" id="id_content">{{post.content}}</textarea>
                </div>
                <div class="form-group mb-3">
                    <p class="lead">Featured Image</p>
                    <input type="file" name="img" class="form-control form-control-lg" id="id_img" value="{{post.img.url}}">
                </div>
                <div class="form-group mb-3">
                    <p class="lead">Status</p>
                    <select name="status" id="id_status" class="form-select form-select-lg" required>
                        <option value="0" {% if post.status == 0 %} selected {% endif %} >Draft</option>
                        <option value="1" {% if post.status == 1 %} selected {% endif %}>Publish</option>
                    </select>
                </div>
                <div class="form-group mb-3">
                    <button type="submit" class="btn btn-lg text-white btn-info">Save Entry</button>
                </div>
            </div>
            </form>

            </div>
             
    </div> 

{% endblock %}

feed/templates/feed/post_user.html
{% extends "feed/base.html" %}

{% block content %}
 <div class="row my-5">
    <div class="col-md-8">
        <p class="display-6 mb-3">@{{ author }}</p>
    </div>
     <div class="col-md-8 mb-3">

        <h3 class="my-2"><i class="bi bi-eye"></i> Published </h3>
        <ul>
            {% if posts %}
                {% for post in posts %}
                <li><a href="{% url 'post_detail' post.author post.slug  %}" target="_blank">{{ post.title }}</a>
                    {% if user.is_authenticated and user == post.author %} | 
                        <a href="{% url 'post_update' post.author post.slug %}">edit post</a>
                    {% endif %}
                </li>
                {% endfor %}        
            {% else %}
            <li>{{ post.author }} has not published anything yet.</li>
        {% endif %}
      </ul>
    </div>
    {% if user.is_authenticated and user == draft.author %}
     <div class="col-md-8">
      <h3 class="my-2"><i class="bi bi-eye-slash"></i> Drafted ({{drafts.count}}) </h3>
        <ul>
            {% if drafts %}
                {% for draft in drafts %}
                <li><a href="{% url 'post_detail' draft.author draft.slug  %}" target="_blank">{{ draft.title }}</a>
                     |
                        <a href="{% url 'post_update' draft.author draft.slug %}">Edit draft</a>
                </li>
                {% endfor %}        
            {% else %}
            <li>{{ post.author }} has not published anything yet.</li>
            {% endif %}
    
      </ul>
   </div>
    {% endif %}

   </div>
{% endblock %}