feed/urls.py
from . import views
from django.urls import include, path

urlpatterns = [
    path("", views.PostList.as_view(), name="feed"),
    path('<str:author>/', views.post_by_user, name='post_by_user'),
    path("<str:author>/create/", views.post_create, name="post_create"),
    path("<str:author>/<slug:slug>/", views.post_detail , name="post_detail"),
    path("<str:author>/<slug:slug>/update", views.post_update, name="post_update"),
    path("<str:author>/<slug:slug>/delete", views.post_delete, name="post_delete"),
    path('<str:author>/<slug:slug>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),

]

kepo/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from myaccount import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', account_views.homepage, name='homepage'),
    #Authentication
    path('signup/', account_views.sign_up, name='sign_up'),
    path('signout/', account_views.sign_out, name='sign_out'),
    path('signin/', account_views.sign_in, name='sign_in'),

    #Webapps
    path('feed/', include('feed.urls')),
    path('journal/', include('myjournal.urls')),
    path('account/', include('myaccount.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myaccount/urls.py
from django.urls import path
from myaccount import views
app_name = 'myaccount'

urlpatterns = [
      path('', views.account_settings, name='account_settings'),
      path('update/', views.account_update, name='account_update'),
      path('password/update', views.password_update, name='password_update'),
      path('sign_in/', views.sign_in, name="sign_in")
]

myjournal/urls.py
from django.urls import path
from django.conf.urls import url

from myjournal import views

app_name = 'myjournal'
urlpatterns = [
    path('today/', views.journal_today, name='journal_today'),
    path('today/morning/create', views.morning_create, name='morning_create'),
    path('morning/<int:morningjournal_pk>/view', views.morning_update, name='morning_update'),
    path('morning/<int:morningjournal_pk>/delete', views.morning_delete, name='morning_delete'),
    path('today/evening/create', views.evening_create, name='evening_create'),
    path('evening/<int:eveningjournal_pk>/view', views.evening_update, name='evening_update'),
    path('evening/<int:eveningjournal_pk>/delete', views.evening_delete, name='evening_delete'),
    path('month/', views.CalendarView.as_view(), name='calendar'),
    path('month/morning/<int:morningjournal_pk>/view', views.morning_update, name='morning_update'),
    path('month/evening/<int:eveningjournal_pk>/view', views.evening_update, name='evening_update'),

]

myjournal/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

MOOD = ((0, "Neutral"), (1, "Silly"), (2, "Dreamy"), (3, "Creative"), (4, "Active"))

class MorningJournal(models.Model):
    title = models.CharField(max_length=200)
    q1a = models.CharField(max_length=200,default="")
    q1b = models.CharField(max_length=200,default="")
    q1c = models.CharField(max_length=200,default="")
    q2a = models.CharField(max_length=200,default="")
    q2b = models.CharField(max_length=200,default="")
    q2c = models.CharField(max_length=200,default="")
    mood = models.IntegerField(choices=MOOD, default=0)
    start_time = models.DateTimeField()
    created_on = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="morning_entries")
    
    @property
    def get_absolute_url(self):
        return reverse('month_calendar_detail', kwargs={'pk': self.pk})
        
class EveningJournal(models.Model):
    title = models.CharField(max_length=200)
    q3a = models.CharField(max_length=200,default="")
    q3b = models.CharField(max_length=200,default="")
    q3c = models.CharField(max_length=200,default="")
    q4a = models.CharField(max_length=200,default="")
    q4b = models.CharField(max_length=200,default="")
    q4c = models.CharField(max_length=200,default="")
    mood = models.IntegerField(choices=MOOD, default=0)
    start_time = models.DateTimeField()
    created_on = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="evening_entries")

    @property
    def get_absolute_url(self):
        url = reverse("myjournal:evening_update", kwargs={"pk": self.pk})
        return f'<a href="{url}"> {self.title}</a>'

myjournal/forms.py
from django.forms import ModelForm, DateInput
from .models import MorningJournal, EveningJournal

class MorningJournalForm(ModelForm):

  class Meta:
    model = MorningJournal
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = {'title','q1a','q1b','q1c','q2a','q2b','q2c','mood','start_time'}

  def __init__(self, *args, **kwargs):
    super(MorningJournalForm, self).__init__(*args, **kwargs)
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['q1a'].required = False
    self.fields['q1b'].required = False
    self.fields['q1c'].required = False
    self.fields['q2a'].required = False
    self.fields['q2b'].required = False
    self.fields['q2c'].required = False

class EveningJournalForm(ModelForm):

  class Meta:
    model = EveningJournal
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = {'title','q3a','q3b','q3c','q4a','q4b','q4c','mood','start_time'}

  def __init__(self, *args, **kwargs):
    super(EveningJournalForm, self).__init__(*args, **kwargs)
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['q3a'].required = False
    self.fields['q3b'].required = False
    self.fields['q3c'].required = False
    self.fields['q4a'].required = False
    self.fields['q4b'].required = False
    self.fields['q4c'].required = False

myjournal/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db import IntegrityError

from django.utils import timezone
from django.utils.safestring import mark_safe

from django.views import generic

import calendar
import random

from datetime import datetime, timedelta, time, date

from .utils import Calendar
from .forms import MorningJournalForm, EveningJournalForm
from .models import MorningJournal, EveningJournal

import os.path
BASE = os.path.dirname(os.path.abspath(__file__))

def journal_count(request):
    today = datetime.now().date()
    #Total Journal Count for a month
    morning_count = MorningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month).count()
    evening_count = EveningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month).count()
    post_count_total = int(morning_count) + int(evening_count)
    return post_count_total

@login_required
def journal_today(request):
    today = datetime.now().date()
    # Filter objects that ranges from today until the next day
    morningjournals = MorningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month,start_time__day=today.day)
    eveningjournals = EveningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month,start_time__day=today.day)
    
    #randomises headline
    questions = open(os.path.join(BASE, "data/questions.txt"))
    data = questions.read().splitlines()
    headline = random.choice(data)

    #Total Journal Count for a month
    morning_count = MorningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month).count()
    evening_count = EveningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month).count()
    post_count_total = int(morning_count) + int(evening_count)

    return render(request, 'myjournal/today.html', {'morningjournals':morningjournals,'eveningjournals':eveningjournals,'today':today,'headline':headline,'post_count_total':post_count_total})

@login_required
def morning_create(request):
    today = datetime.now().date()
    today_datetimelocal = datetime.now().strftime("%Y-%m-%dT%H:%M")
    last7days = datetime.now() - timedelta(7)
    today_datetimelocal_min = last7days.strftime("%Y-%m-%dT%H:%M")

    if request.method == 'GET':
        return render(request, 'myjournal/morning_create.html', {'form':MorningJournalForm(),'today':today,'today_datetimelocal':today_datetimelocal,'today_datetimelocal_min':today_datetimelocal_min})
    else:
        if MorningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month,start_time__day=today.day).exists():
            return render(request, 'myjournal/morning_create.html', {'form':MorningJournalForm(), 'error':'You already made an entry today!','today':today,'today_datetimelocal':today_datetimelocal,'today_datetimelocal_min':today_datetimelocal_min})
        else:
            try:
                form = MorningJournalForm(request.POST)
                new_morningjournal = form.save(commit=False)
                #autopopulates the author model fied with signed in user
                new_morningjournal.author = request.user
                new_morningjournal.save()
                return redirect('myjournal:journal_today')
            except ValueError:
                return render(request, 'myjournal/morning_create.html', {'form':MorningJournalForm(), 'error':'Bad data passed in. Try again.'})

# If you're using a ModelForm then you need to pass an instance of that model to update the object.
@login_required
def morning_update(request, morningjournal_pk):
    morningjournal = get_object_or_404(MorningJournal, pk=morningjournal_pk, author=request.user)
    morningjournal.start_time = morningjournal.start_time.strftime("%Y-%m-%dT%H:%M")
    if request.method == 'GET':
        form = MorningJournalForm(instance=morningjournal)
        return render(request, 'myjournal/morning_update.html', {'morningjournal':morningjournal, 'form':form})
    else:
        try:
            form = MorningJournalForm(request.POST, instance=morningjournal)
            form.save()
            today = datetime.now().date()
            morningjournals = MorningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month,start_time__day=today.day)
            eveningjournals = EveningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month,start_time__day=today.day)
            return render(request, 'myjournal/today.html', {'morningjournal':morningjournal, 'form':form, 'error':'','info':'successfully updated!', 'morningjournals':morningjournals,'eveningjournals':eveningjournals,'today':today})
        except ValueError:
            return render(request, 'myjournal/morning_update.html', {'morningjournal':morningjournal, 'form':form, 'error':'Bad info passed in. Try again?'})

@login_required
def morning_delete(request, morningjournal_pk):
    morningjournal = get_object_or_404(MorningJournal, pk=morningjournal_pk, author=request.user)
    if request.method == 'POST':
        morningjournal.delete()
        return render(request, 'myjournal/today.html', {'morningjournal':morningjournal, 'error':'The post has been deleted'})

@login_required
def evening_create(request):
    today = datetime.now().date()
    today_datetimelocal = datetime.now().strftime("%Y-%m-%dT%H:%M")
    last7days = datetime.now() - timedelta(7)
    today_datetimelocal_min = last7days.strftime("%Y-%m-%dT%H:%M")

    if request.method == 'GET':
        return render(request, 'myjournal/evening_create.html', {'form':EveningJournalForm(),'today':today,'today_datetimelocal':today_datetimelocal,'today_datetimelocal_min':today_datetimelocal_min})
    else:
        if EveningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month,start_time__day=today.day).exists():
            return render(request, 'myjournal/evening_create.html', {'form':EveningJournalForm(), 'error':'You already made an entry today!','today':today,'today_datetimelocal':today_datetimelocal,'today_datetimelocal_min':today_datetimelocal_min})
        else:
            try:
                form = EveningJournalForm(request.POST)
                new_eveningjournal = form.save(commit=False)

                #autopopulates the author model fied with signed in user
                new_eveningjournal.author = request.user
                new_eveningjournal.save()
                return redirect('myjournal:journal_today')
            except ValueError:
                return render(request, 'myjournal/evening_create.html', {'form':EveningJournalForm(), 'error':'Bad data passed in. Try again.'})

@login_required
def evening_update(request, eveningjournal_pk):
    eveningjournal = get_object_or_404(EveningJournal, pk=eveningjournal_pk, author=request.user)
    eveningjournal.start_time = eveningjournal.start_time.strftime("%Y-%m-%dT%H:%M")
    if request.method == 'GET':
        form = EveningJournalForm(instance=eveningjournal)
        return render(request, 'myjournal/evening_update.html', {'eveningjournal':eveningjournal, 'form':form})
    else:
        try:
            form = EveningJournalForm(request.POST, instance=eveningjournal)
            form.save()
            today = datetime.now().date()
            morningjournals = MorningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month,start_time__day=today.day)
            eveningjournals = EveningJournal.objects.filter(author=request.user, start_time__year=today.year,start_time__month=today.month,start_time__day=today.day)
            return render(request, 'myjournal/today.html', {'eveningjournal':eveningjournal, 'form':form, 'error':'','info':'successfully updated!', 'morningjournals':morningjournals,'eveningjournals':eveningjournals,'today':today})
        except ValueError:
            return render(request, 'myjournal/evening_update.html', {'eveningjournal':eveningjournal, 'form':form, 'error':'Bad info passed in. Try again?'})

@login_required
def evening_delete(request, eveningjournal_pk):
    eveningjournal = get_object_or_404(EveningJournal, pk=eveningjournal_pk, author=request.user)
    if request.method == 'POST':
        eveningjournal.delete()
        return render(request, 'myjournal/evening_update.html', {'eveningjournal':eveningjournal, 'error':'The post has been deleted'})

class CalendarView(LoginRequiredMixin, generic.ListView):
    model = MorningJournal
    template_name = 'myjournal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        author = self.request.user
        cal = Calendar(d.year, d.month, author)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)

myjournal/templates/myjournal/calendar.html
{% extends 'myjournal/base.html' %}

{% block title %}
Calendar
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-lg btn-info left" href="{% url 'myjournal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-lg btn-info right" href="{% url 'myjournal:calendar' %}?{{ next_month }}"> Next Month </a>
</div>

{{ calendar }}
{% endblock %}

myjournal/templates/myjournal/evening_create.html
{% extends "myjournal/base.html" %}

{% block content %}
    <h2 class="mt-5">Evening Journal</h2>

    <div class="row">
        <div class="col-md-8">
            {% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
            <form method="POST">
            {% csrf_token %}
            <div class="row g-3">
                <div class="col">
                    <input type="text" name="title" class="form-control form-control-lg" id="id_title" value="Post for {{ today|date:"D, d F Y" }}" 
                    placeholder="Title here" required>
                </div>
                <div class="col">
                    <input type="datetime-local" class="form-control form-control-lg mb-3" name="start_time" value="{{today_datetimelocal}}" 
                        max="{{ today_datetimelocal }}"
                        min="{{ today_datetimelocal_min }}"required="" id="id_start_time">
                </div>
            </div>    
            <div class="col-md-12">
                <p class="lead">3 things I did great today</p>
                <div class="form-group mb-3">
                    <input type="text" name="q3a" class="form-control form-control-lg" id="id_q3a">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q3b" class="form-control form-control-lg" id="id_q3a">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q3c" class="form-control form-control-lg" id="id_q3a">
                </div>

                <p class="lead">3 things that piqued my curiosity today</p>
                <div class="form-group mb-3">
                    <input type="text" name="q4a" class="form-control form-control-lg" id="id_q4a">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q4b" class="form-control form-control-lg" id="id_q4a">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q4c" class="form-control form-control-lg" id="id_q4a">
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-3 lead">This evening, I feel:</label>
                <div class="col-sm-9">
                <select name="mood" id="id_mood" class="form-select form-select-lg" required>
                    <option value="0">Neutral 😶</option>
                    <option value="1">Silly 🤪</option>
                    <option value="2">Dreamy 💭</option>
                    <option value="3">Creative 👨‍🎤</option>
                    <option value="4">Active 💪</option>
                </select>
            </div>
            <div class="col-md-12 mb-5">
                <button type="submit" class="btn btn-lg text-white btn-info">Save Entry</button>
            </div>
            </form>
    </div> 

    <script> 
        function Access() { 
        // Accessing input element type value 
        var a = document.getElementById( "start_time").autocomplete;}
    </script> 

{% endblock %}

myjournal/templates/myjournal/evening_update.html
{% extends "myjournal/base.html" %}

{% block content %}
    <h2 class="mt-5">Update Evening Entry</h2>

    <div class="row">
        <div class="col-md-8">
            {% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
            <form method="POST">
            {% csrf_token %}
            <div class="row g-3">
                <div class="col">
                    <input type="text" name="title" class="form-control form-control-lg" id="id_title" value="Post for {{ today|date:"D, d F Y" }}" 
                    placeholder="Title here" required>
                </div>
                <div class="col">
                    <input type="datetime-local" class="form-control form-control-lg mb-3" name="start_time" value="{{eveningjournal.start_time}}" 
                        max="{{ today_datetimelocal }}"
                        min="{{ today_datetimelocal_min }}"required="" id="id_start_time">
                </div>
            </div>    
            <div class="col-md-12">
                <p class="lead">3 things I did great today!</p>
                <div class="form-group mb-3">
                    <input type="text" name="q1a" class="form-control form-control-lg" id="id_q3a" value="{{eveningjournal.q3a}}">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q1b" class="form-control form-control-lg" id="id_q3b" value="{{eveningjournal.q3b}}">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q1c" class="form-control form-control-lg" id="id_q3c" value="{{eveningjournal.q3c}}">
                </div>

                <p class="lead">3 things that piqued my curiosity</p>
                <div class="form-group mb-3">
                    <input type="text" name="q2a" class="form-control form-control-lg" id="id_q4a" value="{{eveningjournal.q4a}}">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q2b" class="form-control form-control-lg" id="id_q4b" value="{{eveningjournal.q4b}}">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q2c" class="form-control form-control-lg" id="id_q4c" value="{{eveningjournal.q4c}}">
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-3 lead">This evening, I feel:</label>
                <div class="col-sm-9">
                <select name="mood" id="id_mood" class="form-select form-select-lg" required selected="selected">
                    <option value="0" {% if eveningjournal.mood == 0 %} selected {% endif %}>Neutral 😶</option>
                    <option value="1" {% if eveningjournal.mood == 1 %} selected {% endif %}>Silly 🤪</option>
                    <option value="2" {% if eveningjournal.mood == 2 %} selected {% endif %}>Dreamy 💭</option>
                    <option value="3" {% if eveningjournal.mood == 3 %} selected {% endif %}>Creative 👨‍🎤</option>
                    <option value="4" {% if eveningjournal.mood == 4 %} selected {% endif %}>Active 💪</option>
                </select>
            </div>
            <div class="col-md-12 mb-5">
                <button type="submit" class="btn btn-lg text-white btn-info">Update</button>
                <button type="button" class="btn btn-lg text-white btn-danger" onclick="$('#delete').click()">Delete</button>
            </div>
            </form>
            
            <form style='display: none;' method="POST" action="{% url 'myjournal:evening_delete' eveningjournal.id %}">
            {% csrf_token %}
        
                <button id="delete" type="submit">Delete</button>
            </form>
    </div> 


{% endblock %}

myjournal/templates/myjournal/morning_create.html
{% extends "myjournal/base.html" %}

{% block content %}
    <h2 class="mt-5">Morning Journal</h2>

    <div class="row">
        <div class="col-md-8">
            {% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
            <form method="POST">
            {% csrf_token %}
            <div class="row g-3">
                <div class="col">
                    <input type="text" name="title" class="form-control form-control-lg" id="id_title" value="Post for {{ today|date:"D, d F Y" }}" 
                    placeholder="Title here" required>
                </div>
                <div class="col">
                    <input type="datetime-local" class="form-control form-control-lg mb-3" name="start_time" value="{{today_datetimelocal}}" 
                        max="{{ today_datetimelocal }}"
                        min="{{ today_datetimelocal_min }}"required="" id="id_start_time">
                </div>
            </div>    
            <div class="col-md-12">
                <p class="lead">3 things I can start with what I know</p>
                <div class="form-group mb-3">
                    <input type="text" name="q1a" class="form-control form-control-lg" id="id_q1a">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q1b" class="form-control form-control-lg" id="id_q1a">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q1c" class="form-control form-control-lg" id="id_q1a">
                </div>

                <p class="lead">3 things I want to continue learning today</p>
                <div class="form-group mb-3">
                    <input type="text" name="q2a" class="form-control form-control-lg" id="id_q2a">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q2b" class="form-control form-control-lg" id="id_q2a">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q2c" class="form-control form-control-lg" id="id_q2a">
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-3 lead">This morning, I feel:</label>
                <div class="col-sm-9">
                <select name="mood" id="id_mood" class="form-select form-select-lg" required>
                    <option value="0">Neutral 😶</option>
                    <option value="1">Silly 🤪</option>
                    <option value="2">Dreamy 💭</option>
                    <option value="3">Creative 👨‍🎤</option>
                    <option value="4">Active 💪</option>
                </select>
            </div>
            <div class="col-md-12 mb-5">
                <button type="submit" class="btn btn-lg text-white btn-info">Save Entry</button>
            </div>
            </form>
    </div> 

    <script> 
        function Access() { 
        // Accessing input element type value 
        var a = document.getElementById( "start_time").autocomplete;}
    </script> 

{% endblock %}

myjournal/templates/myjournal/morning_update.html
{% extends "myjournal/base.html" %}

{% block content %}
    <h2 class="mt-5">Update Morning Entry</h2>

    <div class="row">
        <div class="col-md-8">
            {% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
            <form method="POST">
            {% csrf_token %}
            <div class="row g-3">
                <div class="col">
                    <input type="text" name="title" class="form-control form-control-lg" id="id_title" value="Post for {{ today|date:"D, d F Y" }}" 
                    placeholder="Title here" required>
                </div>
                <div class="col">
                    <input type="datetime-local" class="form-control form-control-lg mb-3" name="start_time" value="{{morningjournal.start_time}}" 
                        max="{{ today_datetimelocal }}"
                        min="{{ today_datetimelocal_min }}"required="" id="id_start_time">
                </div>
            </div>    
            <div class="col-md-12">
                <p class="lead">3 things I can start with what I know</p>
                <div class="form-group mb-3">
                    <input type="text" name="q1a" class="form-control form-control-lg" id="id_q1a" value="{{morningjournal.q1a}}">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q1b" class="form-control form-control-lg" id="id_q1a" value="{{morningjournal.q1b}}">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q1c" class="form-control form-control-lg" id="id_q1a" value="{{morningjournal.q1c}}">
                </div>

                <p class="lead">3 things I want to continue learning today</p>
                <div class="form-group mb-3">
                    <input type="text" name="q2a" class="form-control form-control-lg" id="id_q2a" value="{{morningjournal.q2a}}">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q2b" class="form-control form-control-lg" id="id_q2a" value="{{morningjournal.q2b}}">
                </div>
                <div class="form-group mb-3">
                    <input type="text" name="q2c" class="form-control form-control-lg" id="id_q2a" value="{{morningjournal.q2c}}">
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-3 lead">This morning, I feel:</label>
                <div class="col-sm-9">
                <select name="mood" id="id_mood" class="form-select form-select-lg" required selected="selected">
                    <option value="0" {% if morningjournal.mood == 0 %} selected {% endif %}>Neutral 😶</option>
                    <option value="1" {% if morningjournal.mood == 1 %} selected {% endif %}>Silly 🤪</option>
                    <option value="2" {% if morningjournal.mood == 2 %} selected {% endif %}>Dreamy 💭</option>
                    <option value="3" {% if morningjournal.mood == 3 %} selected {% endif %}>Creative 👨‍🎤</option>
                    <option value="4" {% if morningjournal.mood == 4 %} selected {% endif %}>Active 💪</option>
                </select>
            </div>
            <div class="col-md-12 mb-5">
                <button type="submit" class="btn btn-lg text-white btn-info">Update</button>
                <button type="button" class="btn btn-lg text-white btn-danger" onclick="$('#delete').click()">Delete</button>
            </div>
            </form>
            
            <form style='display: none;' method="POST" action="{% url 'myjournal:morning_delete' morningjournal.id %}">
            {% csrf_token %}
            
                <button id="delete" type="submit">Delete</button>
            </form>
    </div> 


{% endblock %}