feed/urls.py
from . import views
from django.urls import include, path

urlpatterns = [
    path("", views.PostList.as_view(), name="feed"),
    path('<str:author>/', views.post_by_user, name='post_by_user'),
    path("<str:author>/create/", views.post_create, name="post_create"),
    path("<str:author>/<slug:slug>/", views.post_detail , name="post_detail"),
    path("<str:author>/<slug:slug>/update", views.post_update, name="post_update"),
    path("<str:author>/<slug:slug>/delete", views.post_delete, name="post_delete"),
    path('<str:author>/<slug:slug>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),

]

kepo/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from myaccount import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', account_views.homepage, name='homepage'),
    #Authentication
    path('signup/', account_views.sign_up, name='sign_up'),
    path('signout/', account_views.sign_out, name='sign_out'),
    path('signin/', account_views.sign_in, name='sign_in'),

    #Webapps
    path('feed/', include('feed.urls')),
    path('journal/', include('myjournal.urls')),
    path('account/', include('myaccount.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myaccount/urls.py
from django.urls import path
from myaccount import views
app_name = 'myaccount'

urlpatterns = [
      path('', views.account_settings, name='account_settings'),
      path('update/', views.account_update, name='account_update'),
      path('password/update', views.password_update, name='password_update'),
      path('sign_in/', views.sign_in, name="sign_in")
]

myjournal/urls.py
from django.urls import path
from django.conf.urls import url

from myjournal import views

app_name = 'myjournal'
urlpatterns = [
    path('today/', views.journal_today, name='journal_today'),
    path('today/morning/create', views.morning_create, name='morning_create'),
    path('morning/<int:morningjournal_pk>/view', views.morning_update, name='morning_update'),
    path('morning/<int:morningjournal_pk>/delete', views.morning_delete, name='morning_delete'),
    path('today/evening/create', views.evening_create, name='evening_create'),
    path('evening/<int:eveningjournal_pk>/view', views.evening_update, name='evening_update'),
    path('evening/<int:eveningjournal_pk>/delete', views.evening_delete, name='evening_delete'),
    path('month/', views.CalendarView.as_view(), name='calendar'),
    path('month/morning/<int:morningjournal_pk>/view', views.morning_update, name='morning_update'),
    path('month/evening/<int:eveningjournal_pk>/view', views.evening_update, name='evening_update'),

]

myaccount/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    loc = models.CharField(max_length=30, blank=True)

#  This will auto create a profile of user with blank phone number that can be updated later.
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

myaccount/forms.py
from django import forms
from django.forms import ModelForm, DateInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(UserChangeForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'last_name']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('dob','loc')

myaccount/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, UserUpdateForm, UserProfileForm

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash


def homepage(request):
    return redirect('feed')

def sign_up(request):
    if request.method == 'GET':
        return render(request, 'myaccount/signup.html', {'form':UserRegisterForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    request.POST['username'],
                    password=request.POST['password1'],
                    email=request.POST['email'])
                user.save()
                login(request, user)
                return redirect('myjournal:journal_today')
            except IntegrityError:
                return render(request, 'myaccount/signup.html', {'form':UserRegisterForm(), 'error':'That username has already been taken. Please choose a new username'})
        else:
            return render(request, 'myaccount/signup.html', {'form':UserRegisterForm(), 'error':'Passwords did not match'})

def sign_in(request):
    if request.method == 'GET':
        return render(request, 'myaccount/signin.html', {'form':AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'myaccount/signin.html', {'form':AuthenticationForm(), 'error':'Username and password did not match'})
        else:
            login(request, user)
            return redirect('myjournal:journal_today')

@login_required
def sign_out(request):
    if request.method == 'POST':
        logout(request)
        return redirect('sign_in')

@login_required
def account_settings(request):
    return render(request, 'myaccount/settings.html')

@login_required
def account_update(request):
    if request.method == 'POST':
        form = UserUpdateForm(data=request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            update = form.save(commit=False)
            update.user = request.user
            update.save()
            return render(request, 'myaccount/account_update.html', {'form': form, 'success':"Profile been changed"})
        else:
            return render(request, 'myaccount/account_update.html', {'form': form, 'error':" Bad data passed in. Report error"})   
    else:
        form = UserUpdateForm(instance=request.user)
        return render(request, 'myaccount/account_update.html', {'form': form})   

@login_required
def password_update(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            return render(request, 'myaccount/password_update.html', {'form': form, 'success':"Your password has been successfully changed."})   
        else:
            return render(request, 'myaccount/password_update.html', {'form': form, 'error':"Bad data passed in. Try again"})   
    else:
        form = PasswordChangeForm(request.user)
        return render(request, 'myaccount/password_update.html', {'form': form})

myaccount/templates/myaccount/account_update.html
{% extends "myaccount/base.html" %}

{% block content %}
    <h2 class="mt-5">Account Update</h2>
    <p>Member since {{ user.date_joined }}</p>

    <div class="row">
        <div class="col-md-8">
            {% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
            {% if success %}<div class="alert alert-success" role="alert">{{ success }}</div>{% endif %}
            <form method="POST">
            {% csrf_token %}
            
            <div style="display:none">{{form.as_p}}</div>

            {{profile_form.as_p}}
            <div class="col-md-12">
                <div class="form-group mb-3">
                    <label for="id_username">Username</label>
                    <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" required="" id="id_username" class="form-control form-control-lg" value="{{user.username}}" disabled>
                </div>
                <div class="form-group mb-3">
                    <label for="id_email">Email Address:</label>
                    <input type="email" name="email" maxlength="254" id="id_email" value="{{user.email}}" class="form-control form-control-lg">
                </div>
            </div>
             <div class="row g-3  mb-3">
                <div class="col">
                    <label for="id_first_name">First Name:</label>
                    <input type="text" name="first_name" class="form-control form-control-lg" id="id_first_name" value="{{ user.first_name }}" required>
                </div>
                <div class="col">
                    <label for="id_last_name">Last Name:</label>
                    <input type="text" name="last_name" class="form-control form-control-lg" id="id_last_name" value="{{ user.last_name }}">
                </div>
            </div>    
            <div class="col-md-12 mb-5">
                <button type="submit" class="btn btn-lg text-white btn-info">Update account</button>
            </div>
            </form>

    </div> 

{% endblock %}

myaccount/templates/myaccount/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="KEPO is designed for curious learners and sharers built with Python and Django framework ">
    <meta name="author" content="Kaye So Kua">
    <meta name="generator" content="Hugo 0.80.0">
    <title>KEPO · Curious learning and sharing</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/calendar.css' %}">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="icon" type="image/png"  href="{% static 'images/kepo-uni.png' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: non
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    .bg-pelorous {
        background:#3CC5C5;
    }
    </style>

    <!-- Custom styles for this template -->
    <link href="offcanvas.css" rel="stylesheet">
  </head>
  <body class="bg-light">
    
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-pelorous" aria-label="Main navigation">
  <div class="container">
<a class="navbar-brand" href="{% url 'feed' %}">kepo</a>
    <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="offcanvas" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'myjournal:journal_today' %}">My Journal</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'feed' %}">My Feed</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'myaccount:account_settings' %}">My Account</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>
     

<div class="nav-scroller bg--body shadow-sm">
    <div class="container">
        <nav class="nav nav-underline" aria-label="Secondary navigation">
    <a class="nav-link" aria-current="page" href="{% url 'myaccount:account_update' %}">Update Account</a>
    <a class="nav-link" href="{% url 'myaccount:password_update' %}">
      Change password
    </a>
    <a class="nav-link" href="#" style="float:right">
        You are currently logged in as
      <span class="badge bg-secondary text-white rounded-pill align-text-bottom">
      {{user.username}}</span>
    </a>
  </nav>
    </div>
</div>
 {% endif %}


<main class="container">
    {% block content %}{% endblock %}
  
</main>

  </body>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>

</body>
</html>

myaccount/templates/myaccount/index.html
{% extends "myaccount/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Get started!</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            
            <hr>
            <div class="text-center">
                Need an account? <a href="{% url 'sign_up' %}">Sign Up here</a>
            </div>
            <div class="text-center">
            Forgot password? <a href="{% url 'sign_up' %}">Reset your password here</a>
            </div>
        </div>
    </div>
{% endblock %}

myaccount/templates/myaccount/password_update.html
{% extends "myaccount/base.html" %}

{% block content %}
    <h2 class="mt-5">Password Update</h2>
    <p><i class="bi bi-info-circle"></i> Your password can’t be too similar to your other personal information. <br>
    <i class="bi bi-info-circle"></i> Your password must contain at least 8 characters.<br>
    <i class="bi bi-info-circle"></i> Your password can’t be a commonly used password.<br>
    <i class="bi bi-info-circle"></i> Your password can’t be entirely numeric.<br></p>

    <div class="row">
        <div class="col-md-8">
            {% if error %}<div class="alert alert-danger" role="alert">{{ error }}</div>{% endif %}
            {% if success %}<div class="alert alert-success" role="alert">{{ success }}</div>{% endif %}
            <form method="POST">
            {% csrf_token %}
            
            <div class="col-md-12">
                <div class="form-group mb-3">
                    <label for="id_old_password">Old password:</label>
                    <input type="password" name="old_password" autocomplete="current-password" autofocus="" required="" id="id_old_password" class="form-control form-control-lg" >
                </div>
                <div class="form-group mb-3">
                    <label for="id_new_password1">New password:</label>
                    <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" aria-autocomplete="list" class="form-control form-control-lg" >
                </div>
                <div class="form-group mb-3">
                    <label for="id_new_password2">New password confirmation:</label>
                    <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" class="form-control form-control-lg" >
                </div>
            </div>
            <div class="col-md-12 mb-5">
                <button type="submit" class="btn btn-lg text-white btn-info">Update password</button>
            </div>
            </form>
    </div> 

{% endblock %}

myaccount/templates/myaccount/settings.html
{% extends "myaccount/base.html" %}

{% block content %}

 <div class="row">
    <div class="col-md-8">
        <p class="display-6 my-5">My Account</p>
        <p class="my-5">Member since {{user.date_joined}}</p>

        <p class="my-5"><a href="#" onclick="$('#sign_out_user').click()">Sign Out</a></p>
            <form style='display: none;' method="POST" action="{% url 'sign_out' %}">
                {% csrf_token %}
                <button id="sign_out_user" type="submit">Logout</button>
            </form>
    </div>
</div>
   
{% endblock %}

myaccount/templates/myaccount/signin.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Kepo · Sign In</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  </head>
  <body class="text-center" style="background: var(--kp-pelorous)">
    
<main class="form-signin">
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}

        <form method="POST">
        {% csrf_token %}
    
          <img class="mb-4" src="{% static 'images/kepo.png' %}" alt="" width="72" height="57">
          <h1 class="h3 mb-3 fw-normal text-white">Please sign in</h1>

          <div class="form-floating">
            <input type="text" class="form-control" id="username" name="username">
            <label for="floatingInput">Username</label>
          </div>
          <div class="form-floating">
            <input type="password" class="form-control" id="password" name="password">
            <label for="floatingPassword">Password</label>
          </div>
          <button class="w-100 btn btn-lg btn-light" type="submit">Sign in</button>
        </form>

          <div class="text-center text-white mt-2">
        <a href="{% url 'sign_up' %}" class="btn btn-lg btn-secondary w-100">Create account</a> </br>
    </div>
     <div class="text-center text-white mt-2">
        <a href="{% url 'sign_up' %}" class="link-secondary">Reset your password here</a>
    </div>
</main>
    
  </body>
</html>

myaccount/templates/myaccount/signup.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Kepo · Sign Up</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  </head>
  <body class="text-center" style="background: var(--kp-pelorous)">
    
<main class="form-signin">
   
        <form method="POST">
                {% csrf_token %}
    <img class="mb-4" src="{% static 'images/kepo.png' %}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal text-white">Account Sign Up</h1>
 {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}
    
    <div class="form-floating">
      <input type="text" class="form-control" id="username" name="username" required>
      <label for="floatingInput">Username</label>
    </div>
    
    <div class="form-floating">
      <input type="email" class="form-control" id="email" name="email" required>
      <label for="floatingPassword">Email Address</label>
    </div>

    <div class="form-floating">
      <input type="password" class="form-control" id="password1" name="password1" required>
      <label for="floatingPassword">Password</label>
    </div>

    <div class="form-floating">
      <input type="password" class="form-control" id="password2" name="password2" required>
      <label for="floatingPassword">Repeat Password</label>
    </div>

    <button class="w-100 btn btn-lg btn-light" type="submit">Register</button>
    </form>

    <div class="text-center text-white mt-2">
        <a href="{% url 'sign_up' %}" class="link-secondary">Already have an account? Sign in here.</a>
    </div>
     <div class="text-center text-white mt-2">
        <a href="{% url 'sign_up' %}" class="link-secondary">Reset your password here</a>
    </div>
</main>
    
  </body>
</html>